name: tcc_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  tflite: ^1.1.1
  image_picker: ^0.6.7+10
  pedantic: ^1.9.0
  auto_size_text: ^2.1.0
  cached_network_image: ^2.1.0+1
  badges: 1.1.1
  built_value: ^7.1.0
  dio: ^3.0.9
  date_format: ^1.0.8
  equatable: 1.2.3
  flutter_masked_text: ^0.8.0
  flutter_redux: ^0.6.0
  file_picker: ^1.9.0+1
  graphql: ^3.0.2
  intl: ^0.16.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  introduction_screen: ^1.0.8
  rxdart: ^0.23.1
  url_launcher: 5.5.0
  flutter_html: ^1.0.0
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  reselect: ^0.4.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.8.0
  hive_generator: ^0.7.0+2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/mobilenet_v1_1.0_224.txt
   - assets/mobilenet_v1_1.0_224.tflite
   - assets/yolov2_tiny.tflite
   - assets/yolov2_tiny.txt
   - assets/ssd_mobilenet.tflite
   - assets/ssd_mobilenet.txt
   - assets/deeplabv3_257_mv_gpu.tflite
   - assets/deeplabv3_257_mv_gpu.txt
   - assets/posenet_mv1_075_float_from_checkpoints.tflite
   - assets/detect.tflite
   - assets/labelmap.txt