name: Flutter CI

on:
  push:
    branches: ['feature/*']

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#github-ci'
      if: always()
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      id: setting-up-flutter
      with:
        channel: 'stable'
    - name: Getting Flutter Packages
      id: getting-packages
      run: flutter pub get
    - name: Analyzing code
      id: analyizing-code
      run: flutter analyze
    - name: Running tests
      id: testing-code
      run: flutter test
    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#github-ci'
      if: always()
